package Vista;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;

public class Ocupado extends javax.swing.JFrame {

   
    public Ocupado() {
        initComponents();
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        this.setBackground(new Color(0, 0, 0, 0));
        jPanel1.setBackground(new Color(0, 0, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtEspacio = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnCobrar = new javax.swing.JButton();
        txtTiempo = new javax.swing.JTextField();
        txtMonto = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtPlaca = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtEspacio.setBackground(new Color(0,0,0,0));
        txtEspacio.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        txtEspacio.setText("1");
        txtEspacio.setBorder(null);
        jPanel1.add(txtEspacio, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 30, 60));

        btnCancelar.setText("Cancelar");
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, -1, -1));

        btnCobrar.setText("Cobrar");
        jPanel1.add(btnCobrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, -1, -1));

        txtTiempo.setBackground(new Color(0,0,0,0));
        txtTiempo.setText("jTextField1");
        txtTiempo.setBorder(null);
        txtTiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTiempoActionPerformed(evt);
            }
        });
        jPanel1.add(txtTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 140, 30));

        txtMonto.setBackground(new Color(0,0,0,0));
        txtMonto.setText("jTextField1");
        txtMonto.setBorder(null);
        jPanel1.add(txtMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 140, 30));

        txtNombre.setBackground(new Color(0,0,0,0));
        txtNombre.setText("jTextField1");
        txtNombre.setBorder(null);
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 140, 30));

        txtPlaca.setBackground(new Color(0,0,0,0));
        txtPlaca.setText("jTextField1");
        txtPlaca.setBorder(null);
        jPanel1.add(txtPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 140, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Ocupado.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtTiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTiempoActionPerformed

    }//GEN-LAST:event_txtTiempoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCancelar;
    public javax.swing.JButton btnCobrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField txtEspacio;
    public javax.swing.JTextField txtMonto;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtPlaca;
    public javax.swing.JTextField txtTiempo;
    // End of variables declaration//GEN-END:variables
}
